"""
Faculty Database Schema
=======================
MongoDB schema definitions for Faculty workspace.
"""

COLLECTIONS = {
    "profiles": {
        "faculty_id": "string (required)",
        "first_name": "string (required)",
        "last_name": "string (required)",
        "email": "string (required, unique)",
        "phone": "string",
        "department": "string (required)",
        "designation": "string (required)",
        "qualification": "string",
        "specialization": "string",
        "experience_years": "int",
        "date_of_joining": "datetime",
        "office_location": "string",
        "office_hours": "string",
        "bio": "string",
        "profile_image_url": "string",
        "created_at": "datetime",
        "updated_at": "datetime",
    },
    "classes": {
        "class_name": "string (required)",
        "subject_id": "string (required)",
        "subject_name": "string (required)",
        "course_id": "string (required)",
        "course_name": "string (required)",
        "semester_id": "string (required)",
        "semester_name": "string (required)",
        "department_id": "string (required)",
        "department_name": "string (required)",
        "section": "string (default: A)",
        "academic_year": "string (required)",
        "room": "string",
        "building": "string",
        "total_students": "int",
        "schedule_day": "string (required)",
        "start_time": "string (required)",
        "end_time": "string (required)",
        "faculty_id": "string",
        "status": "string (active/inactive/draft)",
        "last_attendance_date": "datetime",
        "created_at": "datetime",
        "updated_at": "datetime",
    },
    "attendance": {
        "class_id": "string (required)",
        "subject_id": "string",
        "subject_name": "string",
        "student_id": "string (required)",
        "student_name": "string",
        "roll_number": "string",
        "date": "datetime (required)",
        "status": "string (present/absent/late/excused)",
        "remarks": "string",
        "faculty_id": "string",
        "created_at": "datetime",
    },
    "assignments": {
        "title": "string (required)",
        "description": "string",
        "class_id": "string (required)",
        "subject_id": "string (required)",
        "subject_name": "string",
        "total_marks": "float (default: 100)",
        "passing_marks": "float (default: 40)",
        "due_date": "datetime (required)",
        "instructions": "string",
        "attachments": "array[string]",
        "allow_late_submission": "bool (default: false)",
        "late_penalty_percentage": "float (default: 10)",
        "faculty_id": "string",
        "total_submissions": "int",
        "evaluated_count": "int",
        "status": "string (active/draft/archived)",
        "posted_date": "datetime",
        "created_at": "datetime",
        "updated_at": "datetime",
    },
    "assignment_submissions": {
        "assignment_id": "string (required)",
        "student_id": "string (required)",
        "student_name": "string",
        "submission_date": "datetime (required)",
        "marks_obtained": "float",
        "grade": "string",
        "feedback": "string",
        "is_late": "bool",
        "file_url": "string",
        "status": "string (submitted/evaluated)",
        "evaluated_at": "datetime",
    },
    "exams": {
        "exam_name": "string (required)",
        "exam_type": "string (quiz/class_test/mid_semester/end_semester/practical/assignment/project)",
        "class_id": "string (required)",
        "subject_id": "string (required)",
        "subject_name": "string",
        "course_id": "string",
        "semester_id": "string",
        "total_marks": "float (default: 100)",
        "passing_marks": "float (default: 40)",
        "exam_date": "datetime (required)",
        "duration_minutes": "int (default: 60)",
        "start_time": "string",
        "end_time": "string",
        "venue": "string",
        "instructions": "string",
        "faculty_id": "string",
        "total_students": "int",
        "evaluated_count": "int",
        "average_score": "float",
        "highest_score": "float",
        "lowest_score": "float",
        "status": "string (active/draft/completed)",
        "created_at": "datetime",
        "updated_at": "datetime",
    },
    "exam_results": {
        "exam_id": "string (required)",
        "student_id": "string (required)",
        "student_name": "string",
        "roll_number": "string",
        "marks_obtained": "float (required)",
        "max_marks": "float",
        "percentage": "float",
        "grade": "string",
        "remarks": "string",
        "is_absent": "bool",
        "evaluated_at": "datetime",
    },
    "reports": {
        "report_name": "string (required)",
        "report_type": "string (required)",
        "department_id": "string",
        "course_id": "string",
        "semester_id": "string",
        "academic_year": "string",
        "filters": "dict",
        "generated_by": "string",
        "file_url": "string",
        "generated_at": "datetime",
        "status": "string (pending/completed/failed)",
        "created_at": "datetime",
        "updated_at": "datetime",
    },
    "settings": {
        "faculty_id": "string",
        "notification_email": "bool (default: true)",
        "notification_sms": "bool (default: false)",
        "notification_push": "bool (default: true)",
        "default_lecture_duration": "int (default: 60)",
        "default_attendance_threshold": "float (default: 75.0)",
        "auto_close_assignment_days": "int (default: 7)",
        "auto_publish_results": "bool (default: false)",
        "require_student_verification": "bool (default: true)",
        "theme_preference": "string (dark/light)",
        "language_preference": "string (default: en)",
        "created_at": "datetime",
        "updated_at": "datetime",
    },
    "activity_log": {
        "faculty_id": "string",
        "action": "string (required)",
        "actor": "string (required)",
        "module": "string (required)",
        "description": "string",
        "timestamp": "datetime",
    },
}

INDEXES = [
    ("profiles", [("faculty_id", 1)], True),
    ("classes", [("faculty_id", 1), ("semester_id", 1)], False),
    ("attendance", [("class_id", 1), ("date", 1)], False),
    ("attendance", [("student_id", 1)], False),
    ("assignments", [("faculty_id", 1), ("due_date", -1)], False),
    ("exams", [("faculty_id", 1), ("exam_date", -1)], False),
    ("exam_results", [("exam_id", 1), ("student_id", 1)], False),
    ("reports", [("generated_by", 1), ("report_type", 1)], False),
]
